### ISSUE TITLE
Question about adding a new function

### ISSUE THREAD

**Issue by Tigerly** [mesalock-linux/mesatee#1]
Hello,

I'm checking the document of "how to add a function" https://github.com/mesalock-linux/mesatee/blob/master/docs/how_to_add_your_function.md

I have several questions:

1.  after I create a new function, where should I put it?
     should I put it into the folder "mesatee_services/fns/sgx_trusted_lib/src/trusted_worker" or some other place?

2. after registering the new function, should I rebuild the entire MesaTEE framework to make it work?  If not, what should I build for the newly registered function?

3. I guess the newly created function will finally become a part of MesaTEE, and this function will run inside the trusted execution environment as a SGX enclave. Is my understanding correct?

4. I'm curious about the event management part of MesaTEE.
e.g., "On data uploading or new events coming, MesaTEE function services are immediately triggered." mentioned in Examples - https://github.com/mesalock-linux/mesatee/blob/master/examples/README.md
I was wondering how does the MesaTEE framework work for handling the coming events?

Thanks in advance!

**Comment by mssun** [comment]
1. Yes, put it into the `trusted_worker` directory.
2. Yes, you should rebuild the project. We don't support dynamic registration currently.
3. Yes.
4. Function users can use MesaTEE SDK to upload data, approve task, and invoke functions.

BTW, we are working on a more flexible design of function registration and communication. Stay tuned.

**Comment by mssun** [comment]
I'm closing this issue. Feel free to reopen it if you have further questions. Thanks.
