### ISSUE TITLE
Send a request by python socket, the kms crashed

### ISSUE THREAD

**Issue by luoyanhua2011** [mesalock-linux/mesatee#23]
![image-20190823173241-p58w9w](https://user-images.githubusercontent.com/53333864/63923092-85baaa00-ca78-11e9-9495-8304be113514.png)

Send a request without _ssl.CERT_REQUIRED flag by python socket, the kms maybe crashed

**Comment by mssun** [comment]
Please follow this template to report a issue:

```
## Issue

A summary of what the issue is about.

## Steps to Reproduce

Please provide instructions that can be used to reproduce your issue. Usually this will include a test case that produces the wrong output.

## Expected Behavior

What you expected to happen. For example the error message you expected to see.

## Actual Results

What actually happened. For example, an error message you did not expect to see.

## Log

Please attach logs on the screen or in the log file.

## Environment

OS version
Rust version (rustc --version)
SDK version
```

**Comment by luoyanhua2011** [comment]
The original environment has been destroyed, this issue never happened again.
Only OS information can be confirmed, Ubuntu 16.04 LTS

**Comment by mssun** [comment]
I'm closing this issue. Please open a new one if the crash can be reproduced later. Thanks.
