### ISSUE TITLE
how to implement a task to upload data to a http server guarded by TLS

### ISSUE THREAD

**Issue by sammyne** [mesalock-linux/mesatee#28]
Hey~ I wonder if it's possible to trigger a task which would ask the FNS to simply post a "Hello World" string to a http server serving in TLS

**Comment by mssun** [comment]
Thanks for your interests.

First of all, what's the purpose of connecting a HTTP server from a worker?

To ensure the safety of workers, in our design, we want FNS as a delegation of workers for all IO operations (including network). This isolation prevents all possible attack surface via IO. As you may see, we already have APIs to open/save files in DFS with the help of FNS (which may do some authentication, auditing, etc). However, for the network capability you were asking, we haven't seen a need for that. You can prepare input data before starting a task, makes it stateless and predictable.

I hope my short answer can briefly convey our design choice. Feel free to reply if you have further questions. I'll leave this issue open for a couple of days. Thank you so much!

**Comment by mssun** [comment]
I'm closing this issue. Feel free to reopen it or create a new one if you have further questions. Thanks.
