### ISSUE TITLE
tms&fns&tdfs crash when send request by python

### ISSUE THREAD

**Issue by luoyanhua2011** [mesalock-linux/mesatee#36]
tms&fns&tdfs crash when send request by python3 script

mesatee: b78ae148ad348fb3733f31fc4a7429adf56375bd
os: ubuntu-18.04 LTS
sgxsdk: v2.6.100.51363
rust:
    nightly-2019-08-01-x86_64-unknown-linux-gnu (default)
    rustc 1.38.0-nightly (8a58268b5 2019-07-31)
python: v3.6.8

for fns:
![image-fns](https://user-images.githubusercontent.com/53333864/66450080-cd761d80-ea89-11e9-81e5-6d76cc48c618.png)

for tdfs:
![image-tdfs](https://user-images.githubusercontent.com/53333864/66450097-d9fa7600-ea89-11e9-9f9f-5dcb54aa2761.png)

for tms:
![image-tms](https://user-images.githubusercontent.com/53333864/66450113-e088ed80-ea89-11e9-8922-ecdae77767f4.png)

script:
![python](https://user-images.githubusercontent.com/53333864/66450918-dfa58b00-ea8c-11e9-9303-30d218b60cc9.png)

script file:
[crash.zip](https://github.com/mesalock-linux/mesatee/files/3705503/crash.zip)

**Comment by litongxin1991** [comment]
@luoyanhua2011 Thanks for the issue. 

The services are crashed due to large memory allocation. 
In mesatee,  messages are sent with following format: buffer_len+message bytes
```rust
    br.read_exact(&mut lbuf)?;
    let buf_len: u64 = u64::from_be(unsafe { transmute::<[u8; 8], u64>(lbuf) });
    let mut recv_buf: Vec<u8> = vec![0u8; buf_len as usize];
    br.read_exact(&mut recv_buf)?;
```
The messages sent by the python script didn't contain the length field, so several bytes in the json payloads are parsed as the length of the buffer, which are very large.
```
"8872782177770364777" is "{\"task_i"
"8872782280798839354" is "{\"type":"
```

We will fix the issue to avoid crash.

**Comment by hi-T0day** [comment]
Hi, @luoyanhua2011 
I want to know how to open the debug mode as the images in this issue. 
Could you tell me?

Thank you

**Comment by mssun** [comment]
Set the env var: `RUST_LOG=debug`.
