### ISSUE TITLE
HOW TO deploy MesaTEE in k8s

### ISSUE THREAD

**Issue by hi-T0day** [mesalock-linux/mesatee#41]
Hello, 
In this document [Case Study / sensitive-data-computing-over-public-cloud](https://github.com/mesalock-linux/mesatee/blob/master/docs/case_study.md#sensitive-data-computing-over-public-cloud), you wrote:
> Multiple TEE server nodes are grouped together to serve as a cloud cluster, which can be scheduled by orchestration framework like Kubernetes.

I want to build MesaTEE cluster in Kubernetes, just like what you did. 
Could you provide some documents or suggestions about how to deploy MesaTEE in k8s.

Thanks!

**Comment by mssun** [comment]
Thanks @hi-T0day, we are working on distributed worker right now. I think once it’s ready, we can provide a detailed instruction on deploying. If you want to do some experiments on current implementation. We have a docker [image](https://hub.docker.com/r/mesalocklinux/build-mesatee) for building/running MesaTEE.
