### ISSUE TITLE
[WIP] Change interface between FNS and Worker

### ISSUE THREAD

**Issue by litongxin1991** [mesalock-linux/mesatee#8]
Current interface between FNS and Worker needs to be changed.
1. Provide global functions for data reading/writing
    To support mesapy and splited workers, global functions are needed. Then the worker can directly read/write data with context-id/context-token. 
2. A structure for Running Task. 
    The structure will hold the task information, store results and enforce some security policies. 
    The instances of the structure will be saved to the global area. So the above global functions can retrieve the instance and then read/write data. 
3.  A structure for Worker Info and a structure for Worker
4. Worker queue
      The FNS should maintain the available workers

**Comment by mssun** [comment]
Once the PR is merged, we can implemented following C APIs for MesaPy:

```c
int read_file(char* context_id,
              char* context_token,
              char* file_id,
              char* out_buf, size_t out_buf_size);
int save_file_for_all_participants(char* context_id,
                                   char* context_token,
                                   char* in_buf, size_t in_buf_size,
                                   char* file_id, size_t file_id_size);
int save_file_for_task_creator(char* context_id,
                               char* context_token,
                               char* in_buf, size_t in_buf_size,
                               char* file_id, size_t file_id_size);
int save_file_for_file_owner(char* context_id,
                             char* context_token,
                             char* in_buf, size_t in_buf_size,
                             char* file_id,
                             char* new_file_id, size_t new_file_id_size)
```

**Comment by mssun** [comment]
I'll keep this issue open since we need to implement above four C APIs.
